function summaryTable = run_economic_scenario_scan(horizonSteps)
%RUN_ECONOMIC_SCENARIO_SCAN Solve the model across configured methanol-price scenarios.

if nargin < 1 || isempty(horizonSteps)
    horizonSteps = 168;
end

setup_matlab_paths;
modelRoot = fileparts(mfilename('fullpath'));
baseParams = default_model_params(modelRoot);
scenarios = load_codex_folder('market_scenarios', modelRoot);
scenarioNames = fieldnames(scenarios);
scenarioNames = scenarioNames(~strcmp(scenarioNames, 'default'));

n = numel(scenarioNames);
rows = cell(n, 1);

for i = 1:n
    sc = scenarios.(scenarioNames{i});
    p = baseParams;
    p.model.horizon_steps = horizonSteps;
    p.model.methanol_price_yuan_per_kg = sc.methanol_price_yuan_per_kg;
    p.objective.mode = 'max_profit';
    p.solver.verbose = 0;

    results = run_system_optimization(p);
    rows{i} = struct( ...
        'scenario', string(sc.name), ...
        'methanol_price_yuan_per_kg', sc.methanol_price_yuan_per_kg, ...
        'annual_methanol_kg', results.summary.annual_methanol_kg, ...
        'annualized_capex_yuan', results.summary.annualized_capex_yuan, ...
        'grid_cost_yuan', results.summary.grid_cost_yuan, ...
        'curtail_penalty_yuan', results.summary.curtail_penalty_yuan, ...
        'methanol_revenue_yuan', results.summary.methanol_revenue_yuan, ...
        'annual_profit_yuan', results.summary.annual_profit_yuan, ...
        'lcom_yuan_per_kg', results.summary.lcom_yuan_per_kg, ...
        'Ndac', results.capacity.Ndac, ...
        'C_PEM', results.capacity.C_PEM, ...
        'C_batE', results.capacity.C_batE, ...
        'C_batP', results.capacity.C_batP, ...
        'C_CO2', results.capacity.C_CO2, ...
        'C_H2', results.capacity.C_H2);
end

summaryTable = struct2table([rows{:}]);
disp(summaryTable);
end
